/*
 * AccountDetailPaymentEdit.java
 *
 * Created on December 5, 2002, 1:20 PM
 */

package com.maxis.panel;

import com.csgsystems.domain.framework.context.IContext;
import com.csgsystems.domain.framework.businessobject.*;
import com.csgsystems.igpa.forms.ContextFormListener;
import com.csgsystems.igpa.forms.ContextFormEvent;
import com.csgsystems.igpa.utils.ContextFinder;
import com.csgsystems.localization.ResourceManager;
import com.maxis.controls.AccountLocateFinder;

/**
 *
 * @author  prev01
 */
public class AccountDetailPaymentEdit extends javax.swing.JPanel implements ContextFormListener  {
    
    private ContextFinder ctxFinder = new ContextFinder(this);

    /** Creates new form AccountDetailPaymentEdit */
    public AccountDetailPaymentEdit() {
        initComponents();
        ((AccountLocateFinder)alfParentAccountId).setEnabled(true);
        alfParentAccountId.initializeControl();
//        ((AccountLocateFinder)alfParentAccountId).setEditModifyable();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        cbRegulatoryAuthority = new com.csgsystems.igpa.controls.CSGComboBox();
        cbRateClassDefault = new com.csgsystems.igpa.controls.CSGComboBox();
        cbMarketCode = new com.csgsystems.igpa.controls.CSGComboBox();
        cbAccountType = new com.csgsystems.igpa.controls.CSGComboBox();
        cbAccountSegment = new com.csgsystems.igpa.controls.CSGComboBox();
        cbAccountCategory = new com.csgsystems.igpa.controls.CSGComboBox();
        edtStartDate = new com.csgsystems.igpa.controls.CSGDateEdit();
        lblStartDate = new com.csgsystems.igpa.controls.CSGLabel();
        lblParentID = new com.csgsystems.igpa.controls.CSGLabel();
        lblAccountCategory = new com.csgsystems.igpa.controls.CSGLabel();
        lblAccountSegment = new com.csgsystems.igpa.controls.CSGLabel();
        lblAccountType = new com.csgsystems.igpa.controls.CSGLabel();
        lblMarketCode = new com.csgsystems.igpa.controls.CSGLabel();
        lblRateClassDefault = new com.csgsystems.igpa.controls.CSGLabel();
        lblRegulatoryAuthority = new com.csgsystems.igpa.controls.CSGLabel();
        lblPrepaidPostpaid = new com.csgsystems.igpa.controls.CSGLabel();
        lblBillingStatus = new com.csgsystems.igpa.controls.CSGLabel();
        lblChildCount = new com.csgsystems.igpa.controls.CSGLabel();
        lblDisconnectReason = new com.csgsystems.igpa.controls.CSGLabel();
        lblInactiveDate = new com.csgsystems.igpa.controls.CSGLabel();
        edtInactiveDate = new com.csgsystems.igpa.controls.CSGDateEdit();
        edtChildCount = new com.csgsystems.igpa.controls.CSGEdit();
        cbBillingStatus = new com.csgsystems.igpa.controls.CSGComboBox();
        alfParentAccountId = new com.maxis.controls.AccountLocateFinder();
        edtPrePaidPostPaidDisplay = new com.csgsystems.igpa.controls.CSGEdit();
        edtDisconnectReason = new com.csgsystems.igpa.controls.CSGEdit();
        jPanel2 = new javax.swing.JPanel();
        cbPaymentMethod = new com.csgsystems.igpa.controls.CSGComboBox();
        pnlPaymentMethodCreditCard = new javax.swing.JPanel();
        cSGLabel1 = new com.csgsystems.igpa.controls.CSGLabel();
        cSGLabel2 = new com.csgsystems.igpa.controls.CSGLabel();
        cSGLabel3 = new com.csgsystems.igpa.controls.CSGLabel();
        cSGLabel4 = new com.csgsystems.igpa.controls.CSGLabel();
        cbCreditCardType = new com.csgsystems.igpa.controls.CSGComboBox();
        edtCreditCardNumber = new com.csgsystems.igpa.controls.CSGEdit();
        edtHolderName = new com.csgsystems.igpa.controls.CSGEdit();
        jLabel1 = new javax.swing.JLabel();
        edtExpireDate = new com.csgsystems.igpa.controls.CSGEdit();
        localizedLabel1 = new com.csgsystems.igpa.controls.CSGLabel();
        cSGComboBox1 = new com.csgsystems.igpa.controls.CSGComboBox();
        cSGLabel12 = new com.csgsystems.igpa.controls.CSGLabel();
        clearingHouse1 = new com.csgsystems.igpa.controls.CSGComboBox();
        pnlPaymentMethodDirectDebit = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cSGLabel5 = new com.csgsystems.igpa.controls.CSGLabel();
        cSGLabel6 = new com.csgsystems.igpa.controls.CSGLabel();
        cSGLabel7 = new com.csgsystems.igpa.controls.CSGLabel();
        edtBankRoutingNumber = new com.csgsystems.igpa.controls.CSGEdit();
        edtBankName = new com.csgsystems.igpa.controls.CSGEdit();
        edtBankAccount = new com.csgsystems.igpa.controls.CSGEdit();
        cSGLabel8 = new com.csgsystems.igpa.controls.CSGLabel();
        cSGLabel9 = new com.csgsystems.igpa.controls.CSGLabel();
        cSGLabel10 = new com.csgsystems.igpa.controls.CSGLabel();
        cSGLabel11 = new com.csgsystems.igpa.controls.CSGLabel();
        edtAlternateBank = new com.csgsystems.igpa.controls.CSGEdit();
        edtBankAgencyCode = new com.csgsystems.igpa.controls.CSGEdit();
        edtBankAgencyName = new com.csgsystems.igpa.controls.CSGEdit();
        clearingHouse = new com.csgsystems.igpa.controls.CSGComboBox();

        setLayout(null);

        setPreferredSize(new java.awt.Dimension(640, 380));
        jPanel1.setLayout(null);

        jPanel1.setBorder(new javax.swing.border.TitledBorder(ResourceManager.getString( "AccountDetails.title.AccountDetails" )));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 300));
        cbRegulatoryAuthority.setAttributeName("RegulatoryId");
        cbRegulatoryAuthority.setDomainName("Account");
        jPanel1.add(cbRegulatoryAuthority);
        cbRegulatoryAuthority.setBounds(150, 270, 150, 20);

        cbRateClassDefault.setAttributeName("RateClassDefault");
        cbRateClassDefault.setDomainName("Account");
        jPanel1.add(cbRateClassDefault);
        cbRateClassDefault.setBounds(150, 245, 150, 20);

        cbMarketCode.setAttributeName("MktCode");
        cbMarketCode.setDomainName("Account");
        jPanel1.add(cbMarketCode);
        cbMarketCode.setBounds(150, 220, 150, 20);

        cbAccountType.setAttributeName("AccountType");
        cbAccountType.setDomainName("Account");
        jPanel1.add(cbAccountType);
        cbAccountType.setBounds(150, 195, 150, 20);

        cbAccountSegment.setAttributeName("AcctSegId");
        cbAccountSegment.setDomainName("Account");
        jPanel1.add(cbAccountSegment);
        cbAccountSegment.setBounds(150, 145, 150, 20);

        cbAccountCategory.setAttributeName("AccountCategory");
        cbAccountCategory.setDomainName("Account");
        cbAccountCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAccountCategoryActionPerformed(evt);
            }
        });

        jPanel1.add(cbAccountCategory);
        cbAccountCategory.setBounds(150, 120, 150, 20);

        edtStartDate.setAttributeName("DateActive");
        edtStartDate.setDomainName("Account");
        edtStartDate.setEnabled(false);
        jPanel1.add(edtStartDate);
        edtStartDate.setBounds(150, 20, 150, 20);

        lblStartDate.setLocalizationKey("AccountDetails.lblStartDate");
        jPanel1.add(lblStartDate);
        lblStartDate.setBounds(10, 20, 140, 20);

        lblParentID.setLocalizationKey("AccountDetails.lblParentID");
        jPanel1.add(lblParentID);
        lblParentID.setBounds(10, 70, 140, 20);

        lblAccountCategory.setLocalizationKey("AccountDetails.lblAccountCategory");
        jPanel1.add(lblAccountCategory);
        lblAccountCategory.setBounds(10, 120, 140, 20);

        lblAccountSegment.setLocalizationKey("AccountDetails.lblAccountSegment");
        jPanel1.add(lblAccountSegment);
        lblAccountSegment.setBounds(10, 145, 140, 20);

        lblAccountType.setLocalizationKey("AccountDetails.lblAccountType");
        jPanel1.add(lblAccountType);
        lblAccountType.setBounds(10, 195, 140, 20);

        lblMarketCode.setLocalizationKey("AccountDetails.lblMarketCode");
        jPanel1.add(lblMarketCode);
        lblMarketCode.setBounds(10, 220, 140, 20);

        lblRateClassDefault.setLocalizationKey("AccountDetails.lblRateClassDefault");
        jPanel1.add(lblRateClassDefault);
        lblRateClassDefault.setBounds(10, 245, 140, 20);

        lblRegulatoryAuthority.setLocalizationKey("AccountDetails.lblRegulatoryAuthority");
        jPanel1.add(lblRegulatoryAuthority);
        lblRegulatoryAuthority.setBounds(10, 270, 140, 20);

        lblPrepaidPostpaid.setLocalizationKey("AccountDetails.lblPrepaidPostpaid");
        jPanel1.add(lblPrepaidPostpaid);
        lblPrepaidPostpaid.setBounds(10, 170, 140, 20);

        lblBillingStatus.setLocalizationKey("AccountDetails.lblBillingStatus");
        jPanel1.add(lblBillingStatus);
        lblBillingStatus.setBounds(10, 295, 140, 20);

        lblChildCount.setLocalizationKey("AccountDetails.lblChildCount");
        jPanel1.add(lblChildCount);
        lblChildCount.setBounds(10, 95, 140, 20);

        lblDisconnectReason.setLocalizationKey("AccountDetails.lblDisconnectReason");
        jPanel1.add(lblDisconnectReason);
        lblDisconnectReason.setBounds(10, 320, 140, 20);

        lblInactiveDate.setLocalizationKey("AccountDetails.lblInactiveDate");
        jPanel1.add(lblInactiveDate);
        lblInactiveDate.setBounds(10, 45, 140, 20);

        edtInactiveDate.setAttributeName("DateInactive");
        edtInactiveDate.setDomainName("Account");
        jPanel1.add(edtInactiveDate);
        edtInactiveDate.setBounds(150, 45, 150, 20);

        edtChildCount.setAttributeName("ChildCount");
        edtChildCount.setDomainName("Account");
        edtChildCount.setEnabled(false);
        jPanel1.add(edtChildCount);
        edtChildCount.setBounds(150, 95, 150, 20);

        cbBillingStatus.setAtomName("AccountStatus");
        cbBillingStatus.setDomainName("Account");
        jPanel1.add(cbBillingStatus);
        cbBillingStatus.setBounds(150, 295, 150, 20);

        alfParentAccountId.setAttributeName("ParentAccountExternalId");
        alfParentAccountId.setBigfootObject("Account");
        alfParentAccountId.setDomainName("Account");
        jPanel1.add(alfParentAccountId);
        alfParentAccountId.setBounds(150, 70, 150, 20);

        edtPrePaidPostPaidDisplay.setAttributeName("PrePaidPostPaidDisplay");
        edtPrePaidPostPaidDisplay.setDomainName("Account");
        jPanel1.add(edtPrePaidPostPaidDisplay);
        edtPrePaidPostPaidDisplay.setBounds(150, 170, 150, 20);

        edtDisconnectReason.setAttributeName("DisconnectReason");
        edtDisconnectReason.setDomainName("Account");
        jPanel1.add(edtDisconnectReason);
        edtDisconnectReason.setBounds(150, 320, 150, 20);

        add(jPanel1);
        jPanel1.setBounds(5, 5, 310, 360);

        jPanel2.setLayout(null);

        jPanel2.setBorder(new javax.swing.border.TitledBorder(ResourceManager.getString( "AccountDetails.title.PaymentMethod" )));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 300));
        cbPaymentMethod.setAttributeName("PayMethod");
        cbPaymentMethod.setDomainName("Account");
        cbPaymentMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPaymentMethodActionPerformed(evt);
            }
        });

        jPanel2.add(cbPaymentMethod);
        cbPaymentMethod.setBounds(10, 20, 290, 20);

        pnlPaymentMethodCreditCard.setLayout(null);

        cSGLabel1.setLocalizationKey("AccountPaymentMethod.lblExpirationDate");
        pnlPaymentMethodCreditCard.add(cSGLabel1);
        cSGLabel1.setBounds(10, 85, 130, 20);

        cSGLabel2.setLocalizationKey("AccountPaymentMethod.lblHolderName");
        pnlPaymentMethodCreditCard.add(cSGLabel2);
        cSGLabel2.setBounds(10, 60, 130, 20);

        cSGLabel3.setLocalizationKey("AccountPaymentMethod.lblCreditCardNumber");
        pnlPaymentMethodCreditCard.add(cSGLabel3);
        cSGLabel3.setBounds(10, 35, 130, 20);

        cSGLabel4.setLocalizationKey("AccountPaymentMethod.lblCreditCardType");
        pnlPaymentMethodCreditCard.add(cSGLabel4);
        cSGLabel4.setBounds(10, 10, 130, 20);

        cbCreditCardType.setAttributeName("CcardCarrier");
        cbCreditCardType.setDomainName("Account");
        pnlPaymentMethodCreditCard.add(cbCreditCardType);
        cbCreditCardType.setBounds(140, 10, 150, 20);

        edtCreditCardNumber.setAttributeName("CcardAccount");
        edtCreditCardNumber.setDomainName("Account");
        pnlPaymentMethodCreditCard.add(edtCreditCardNumber);
        edtCreditCardNumber.setBounds(140, 35, 150, 20);

        edtHolderName.setAttributeName("CcardOwnrName");
        edtHolderName.setDomainName("Account");
        pnlPaymentMethodCreditCard.add(edtHolderName);
        edtHolderName.setBounds(140, 60, 150, 20);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/csgsystems/bp/images/TreeFiveBranch.gif")));
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlPaymentMethodCreditCard.add(jLabel1);
        jLabel1.setBounds(0, 0, 10, 125);

        edtExpireDate.setAttributeName("CcardExpire");
        edtExpireDate.setDomainName("Account");
        pnlPaymentMethodCreditCard.add(edtExpireDate);
        edtExpireDate.setBounds(140, 85, 150, 20);

        localizedLabel1.setLocalizationKey("AccountPaymentMethod.lblTransType");
        pnlPaymentMethodCreditCard.add(localizedLabel1);
        localizedLabel1.setBounds(10, 110, 100, 20);

        cSGComboBox1.setAttributeName("TransFlag");
        cSGComboBox1.setDomainName("Account");
        pnlPaymentMethodCreditCard.add(cSGComboBox1);
        cSGComboBox1.setBounds(140, 110, 150, 20);

        cSGLabel12.setLocalizationKey("AccountPaymentMethod.lblClearingHouse");
        pnlPaymentMethodCreditCard.add(cSGLabel12);
        cSGLabel12.setBounds(10, 135, 130, 20);

        clearingHouse1.setAttributeName("CcardClearingHouseId");
        clearingHouse1.setDomainName("Account");
        pnlPaymentMethodCreditCard.add(clearingHouse1);
        clearingHouse1.setBounds(140, 135, 150, 20);

        jPanel2.add(pnlPaymentMethodCreditCard);
        pnlPaymentMethodCreditCard.setBounds(10, 45, 290, 0);

        pnlPaymentMethodDirectDebit.setLayout(null);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/csgsystems/bp/images/TreeSevenBranch.gif")));
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pnlPaymentMethodDirectDebit.add(jLabel2);
        jLabel2.setBounds(0, 0, 10, 180);

        cSGLabel5.setLocalizationKey("AccountPaymentMethod.lblBankAccount");
        pnlPaymentMethodDirectDebit.add(cSGLabel5);
        cSGLabel5.setBounds(10, 10, 130, 20);

        cSGLabel6.setLocalizationKey("AccountPaymentMethod.lblBankName");
        pnlPaymentMethodDirectDebit.add(cSGLabel6);
        cSGLabel6.setBounds(10, 35, 130, 20);

        cSGLabel7.setLocalizationKey("AccountPaymentMethod.lblBankRoutingNumber");
        pnlPaymentMethodDirectDebit.add(cSGLabel7);
        cSGLabel7.setBounds(10, 60, 130, 20);

        edtBankRoutingNumber.setAttributeName("CustBankSortCode");
        edtBankRoutingNumber.setDomainName("Account");
        pnlPaymentMethodDirectDebit.add(edtBankRoutingNumber);
        edtBankRoutingNumber.setBounds(140, 60, 150, 20);

        edtBankName.setAttributeName("CustBankAccName");
        edtBankName.setDomainName("Account");
        pnlPaymentMethodDirectDebit.add(edtBankName);
        edtBankName.setBounds(140, 35, 150, 20);

        edtBankAccount.setAttributeName("CustBankAccNum");
        edtBankAccount.setDomainName("Account");
        pnlPaymentMethodDirectDebit.add(edtBankAccount);
        edtBankAccount.setBounds(140, 10, 150, 20);

        cSGLabel8.setLocalizationKey("AccountPaymentMethod.lblBankAgencyName");
        pnlPaymentMethodDirectDebit.add(cSGLabel8);
        cSGLabel8.setBounds(10, 85, 130, 20);

        cSGLabel9.setLocalizationKey("AccountPaymentMethod.lblBankAgencyCode");
        pnlPaymentMethodDirectDebit.add(cSGLabel9);
        cSGLabel9.setBounds(10, 110, 130, 20);

        cSGLabel10.setLocalizationKey("AccountPaymentMethod.lblAlternateBank");
        pnlPaymentMethodDirectDebit.add(cSGLabel10);
        cSGLabel10.setBounds(10, 135, 130, 20);

        cSGLabel11.setLocalizationKey("AccountPaymentMethod.lblClearingHouse");
        pnlPaymentMethodDirectDebit.add(cSGLabel11);
        cSGLabel11.setBounds(10, 160, 130, 20);

        edtAlternateBank.setAttributeName("AltBankAccNum");
        edtAlternateBank.setDomainName("Account");
        pnlPaymentMethodDirectDebit.add(edtAlternateBank);
        edtAlternateBank.setBounds(140, 135, 150, 20);

        edtBankAgencyCode.setAttributeName("BankAgencyCode");
        edtBankAgencyCode.setDomainName("Account");
        pnlPaymentMethodDirectDebit.add(edtBankAgencyCode);
        edtBankAgencyCode.setBounds(140, 110, 150, 20);

        edtBankAgencyName.setAttributeName("BankAgencyName");
        edtBankAgencyName.setDomainName("Account");
        pnlPaymentMethodDirectDebit.add(edtBankAgencyName);
        edtBankAgencyName.setBounds(140, 85, 150, 20);

        clearingHouse.setAttributeName("ClearingHouseId");
        clearingHouse.setDomainName("Account");
        pnlPaymentMethodDirectDebit.add(clearingHouse);
        clearingHouse.setBounds(140, 160, 150, 20);

        jPanel2.add(pnlPaymentMethodDirectDebit);
        pnlPaymentMethodDirectDebit.setBounds(10, 45, 290, 0);

        add(jPanel2);
        jPanel2.setBounds(320, 5, 310, 360);

    }//GEN-END:initComponents

    public void contextFormStateChanged(ContextFormEvent contextFormEvent) { 
        if (contextFormEvent.getType() == ContextFormEvent.POST_OPEN ) {
            setupPayMethod();
        }
    }
    
    private void cbAccountCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAccountCategoryActionPerformed
        edtPrePaidPostPaidDisplay.initializeControl();
    }//GEN-LAST:event_cbAccountCategoryActionPerformed

    private void cbPaymentMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPaymentMethodActionPerformed
        setupPayMethod();
    }//GEN-LAST:event_cbPaymentMethodActionPerformed

    private void setupPayMethod() {  
        IContext ctx = ctxFinder.findContext();
        IPersistentObject acct = ctx.getObject("Account", null);
        int payMethod = acct.getAttributeDataAsInteger("PayMethod");
        switch(payMethod) {
            case -1:
            case 0:
            case 1:
                // none selected or check
                pnlPaymentMethodDirectDebit.setEnabled(true);
                pnlPaymentMethodDirectDebit.setBounds(15, 40, 290, 0);
                pnlPaymentMethodCreditCard.setEnabled(false);
                pnlPaymentMethodCreditCard.setBounds(15, 40, 290, 0);
                break;
            case 2:
                // credit card
                pnlPaymentMethodDirectDebit.setEnabled(false);
                pnlPaymentMethodDirectDebit.setBounds(15, 40, 290, 0);
                pnlPaymentMethodCreditCard.setEnabled(true);
                pnlPaymentMethodCreditCard.setBounds(15, 40, 290, 155);
                // Reset Controls
                cbCreditCardType.initializeControl();
                edtCreditCardNumber.initializeControl();
                edtHolderName.initializeControl();
                edtExpireDate.initializeControl();
                break;
            case 3:
                // direct debit
                pnlPaymentMethodDirectDebit.setEnabled(false);
                pnlPaymentMethodDirectDebit.setBounds(15, 40, 290, 190);
                pnlPaymentMethodCreditCard.setEnabled(false);
                pnlPaymentMethodCreditCard.setBounds(15, 40, 290, 0);
                // Reset Controls on this Panel
                edtBankAccount.initializeControl();
                edtBankName.initializeControl();
                edtBankRoutingNumber.initializeControl();
                edtBankAgencyName.initializeControl();
                edtBankAgencyCode.initializeControl();
                edtAlternateBank.initializeControl();
                clearingHouse.initializeControl(); // Clearing House Id
                break;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.maxis.controls.AccountLocateFinder alfParentAccountId;
    private com.csgsystems.igpa.controls.CSGComboBox cSGComboBox1;
    private com.csgsystems.igpa.controls.CSGLabel cSGLabel1;
    private com.csgsystems.igpa.controls.CSGLabel cSGLabel10;
    private com.csgsystems.igpa.controls.CSGLabel cSGLabel11;
    private com.csgsystems.igpa.controls.CSGLabel cSGLabel12;
    private com.csgsystems.igpa.controls.CSGLabel cSGLabel2;
    private com.csgsystems.igpa.controls.CSGLabel cSGLabel3;
    private com.csgsystems.igpa.controls.CSGLabel cSGLabel4;
    private com.csgsystems.igpa.controls.CSGLabel cSGLabel5;
    private com.csgsystems.igpa.controls.CSGLabel cSGLabel6;
    private com.csgsystems.igpa.controls.CSGLabel cSGLabel7;
    private com.csgsystems.igpa.controls.CSGLabel cSGLabel8;
    private com.csgsystems.igpa.controls.CSGLabel cSGLabel9;
    private com.csgsystems.igpa.controls.CSGComboBox cbAccountCategory;
    private com.csgsystems.igpa.controls.CSGComboBox cbAccountSegment;
    private com.csgsystems.igpa.controls.CSGComboBox cbAccountType;
    private com.csgsystems.igpa.controls.CSGComboBox cbBillingStatus;
    private com.csgsystems.igpa.controls.CSGComboBox cbCreditCardType;
    private com.csgsystems.igpa.controls.CSGComboBox cbMarketCode;
    private com.csgsystems.igpa.controls.CSGComboBox cbPaymentMethod;
    private com.csgsystems.igpa.controls.CSGComboBox cbRateClassDefault;
    private com.csgsystems.igpa.controls.CSGComboBox cbRegulatoryAuthority;
    private com.csgsystems.igpa.controls.CSGComboBox clearingHouse;
    private com.csgsystems.igpa.controls.CSGComboBox clearingHouse1;
    private com.csgsystems.igpa.controls.CSGEdit edtAlternateBank;
    private com.csgsystems.igpa.controls.CSGEdit edtBankAccount;
    private com.csgsystems.igpa.controls.CSGEdit edtBankAgencyCode;
    private com.csgsystems.igpa.controls.CSGEdit edtBankAgencyName;
    private com.csgsystems.igpa.controls.CSGEdit edtBankName;
    private com.csgsystems.igpa.controls.CSGEdit edtBankRoutingNumber;
    private com.csgsystems.igpa.controls.CSGEdit edtChildCount;
    private com.csgsystems.igpa.controls.CSGEdit edtCreditCardNumber;
    private com.csgsystems.igpa.controls.CSGEdit edtDisconnectReason;
    private com.csgsystems.igpa.controls.CSGEdit edtExpireDate;
    private com.csgsystems.igpa.controls.CSGEdit edtHolderName;
    private com.csgsystems.igpa.controls.CSGDateEdit edtInactiveDate;
    private com.csgsystems.igpa.controls.CSGEdit edtPrePaidPostPaidDisplay;
    private com.csgsystems.igpa.controls.CSGDateEdit edtStartDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.csgsystems.igpa.controls.CSGLabel lblAccountCategory;
    private com.csgsystems.igpa.controls.CSGLabel lblAccountSegment;
    private com.csgsystems.igpa.controls.CSGLabel lblAccountType;
    private com.csgsystems.igpa.controls.CSGLabel lblBillingStatus;
    private com.csgsystems.igpa.controls.CSGLabel lblChildCount;
    private com.csgsystems.igpa.controls.CSGLabel lblDisconnectReason;
    private com.csgsystems.igpa.controls.CSGLabel lblInactiveDate;
    private com.csgsystems.igpa.controls.CSGLabel lblMarketCode;
    private com.csgsystems.igpa.controls.CSGLabel lblParentID;
    private com.csgsystems.igpa.controls.CSGLabel lblPrepaidPostpaid;
    private com.csgsystems.igpa.controls.CSGLabel lblRateClassDefault;
    private com.csgsystems.igpa.controls.CSGLabel lblRegulatoryAuthority;
    private com.csgsystems.igpa.controls.CSGLabel lblStartDate;
    private com.csgsystems.igpa.controls.CSGLabel localizedLabel1;
    private javax.swing.JPanel pnlPaymentMethodCreditCard;
    private javax.swing.JPanel pnlPaymentMethodDirectDebit;
    // End of variables declaration//GEN-END:variables
    
}
