/*
 * AggrNewCustAcqSummary.java
 *
 * Created on August 27, 2002, 1:52 PM
 */

package com.maxis.panel;

import com.csgsystems.localization.ResourceManager;
 
/**
 *
 * @author  andr01
 */
public class AggrNewCustAcqSummaryFinalConf extends javax.swing.JPanel {
    
    /** Creates new form AggrNewCustAcqSummary */
    public AggrNewCustAcqSummaryFinalConf() {
        initComponents();
        
        AccountConfirmationFinalConf panelAccountSummary = new AccountConfirmationFinalConf();
        OrderConfirmation panelOrderSummary = new OrderConfirmation();
        
        tpNewCustomerAcqSummary.add(ResourceManager.getString("AggrNewCustAcqSummaryFinalConf.tab.Summary"), panelAccountSummary);
        tpNewCustomerAcqSummary.add(ResourceManager.getString("AggrNewCustAcqSummaryFinalConf.tab.Order"), panelOrderSummary);
        System.out.println("added both the panels are tabs");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tpNewCustomerAcqSummary = new javax.swing.JTabbedPane();

        setLayout(new java.awt.GridBagLayout());

        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(990, 620));
        tpNewCustomerAcqSummary.setMaximumSize(null);
        tpNewCustomerAcqSummary.setMinimumSize(new java.awt.Dimension(400, 400));
        tpNewCustomerAcqSummary.setPreferredSize(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(tpNewCustomerAcqSummary, gridBagConstraints);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tpNewCustomerAcqSummary;
    // End of variables declaration//GEN-END:variables
    
}
