/*
 * BaseAccountAlternateAddress.java
 *
 * Created on August 22, 2002, 3:24 PM
 */

package com.maxis.panel;

import com.csgsystems.domain.framework.businessobject.IPersistentObject;
import com.csgsystems.domain.framework.context.IContext;
import com.csgsystems.igpa.controls.BoundDataChangeEvent;
import com.csgsystems.igpa.controls.BoundDataChangeListener;
import com.csgsystems.igpa.forms.ContextFormEvent;
import com.csgsystems.igpa.forms.ContextFormListener;
import com.csgsystems.igpa.utils.ContextFinder;

import com.csgsystems.localization.ResourceManager;

/**
 *
 * @author  mccm06
 */
public class BaseAccountAlternateAddress extends javax.swing.JPanel implements ContextFormListener {
    
    /**
     *  Instance of the ContextFinder utility class, which can recursively
     *  search up the component hierarchy for an ICSGContextForm, and then
     *  retrieve its context (cached for later use).
     */
    private ContextFinder ctxFinder = new ContextFinder(this);
    
    /** Creates new form BaseAccountAlternateAddress */
    public BaseAccountAlternateAddress() {
        initComponents();
    }
    
    public void contextFormStateChanged(com.csgsystems.igpa.forms.ContextFormEvent contextFormEvent) {
        if (ContextFormEvent.POST_INIT_CONTROLS == contextFormEvent.getType()) {
            // add a listener to the controls that make up a geocode find
            edtCity.addBoundDataChangeListener(new BoundDataChangeListener() {
                    public void boundDataChanged(BoundDataChangeEvent bdce) {
                        doGeocodeFind();
                    }
                });    
                
            edtStateProv.addBoundDataChangeListener(new BoundDataChangeListener() {
                    public void boundDataChanged(BoundDataChangeEvent bdce) {
                        doGeocodeFind();
                    }
                });  
            
            edtZipPostalCode.addBoundDataChangeListener(new BoundDataChangeListener() {
                    public void boundDataChanged(BoundDataChangeEvent bdce) {
                        doGeocodeFind();
                        edtCity.initializeControl();
                        edtStateProv.initializeControl();
                    }
                });  
            
            cbCountry.addBoundDataChangeListener(new BoundDataChangeListener() {
                    public void boundDataChanged(BoundDataChangeEvent bdce) {
                        doGeocodeFind();
                        changeCityState();
                    }
                });  
            
            cbFranchise.addBoundDataChangeListener(new BoundDataChangeListener() {
                    public void boundDataChanged(BoundDataChangeEvent bdce) {
                        doGeocodeFind();
                    }
                });   
            
            IContext ctx = ctxFinder.findContext();
            IPersistentObject account = ctx.getObject("Account", null);
            if (account.getAttributeDataAsBoolean("VirtualIsCountyFreeForm") == true) {
//                ccbCustCounty.setVisible(false);
//                edtCounty.setVisible(true);
                edtCustGeocode.setVisible(false);
                lblCustGeocode.setVisible(false);
            } else {
//                ccbCustCounty.setVisible(true);
//                edtCounty.setVisible(false);
                edtCustGeocode.setVisible(true);
                lblCustGeocode.setVisible(true);                
            }
        }
    }
    
    private void changeCityState() {
        IContext ctx = ctxFinder.findContext();
        IPersistentObject account = ctx.getObject("Account", null);
        
        if ( account.getAttributeDataAsInteger("CustCountryCode") == 458 ) {
            account.getAttribute("CustState").setReadOnly(true);
            account.getAttribute("CustCity").setReadOnly(true);
            edtCity.initializeControl();
            edtStateProv.initializeControl();
        } else {
            account.getAttribute("CustState").setReadOnly(false);
            account.getAttribute("CustCity").setReadOnly(false);
            edtCity.initializeControl();
            edtStateProv.initializeControl();            
        }
    }
    
    private void doGeocodeFind() {
        IContext ctx = ctxFinder.findContext();
        IPersistentObject account = ctx.getObject("Account", null);
        
        account.sendMessage("resetGeocodeCustomerAddressList", null);
//        ccbCustCounty.initializeControl();
        edtCustGeocode.initializeControl();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        edtCustGeocode = new com.csgsystems.igpa.controls.CSGEdit();
        lblCustGeocode = new com.csgsystems.igpa.controls.CSGLabel();
        edtAddressLine3 = new com.csgsystems.igpa.controls.CSGEdit();
        cbFranchise = new com.csgsystems.igpa.controls.CSGComboBox();
        cbCountry = new com.csgsystems.igpa.controls.CSGComboBox();
        lblFranchise = new com.csgsystems.igpa.controls.CSGLabel();
        lblCountry = new com.csgsystems.igpa.controls.CSGLabel();
        edtZipPostalCode = new com.csgsystems.igpa.controls.CSGEdit();
        lblZipPostalCode = new com.csgsystems.igpa.controls.CSGLabel();
        lblStateProv = new com.csgsystems.igpa.controls.CSGLabel();
        lblCity = new com.csgsystems.igpa.controls.CSGLabel();
        edtStateProv = new com.csgsystems.igpa.controls.CSGEdit();
        edtCity = new com.csgsystems.igpa.controls.CSGEdit();
        edtAddressLine2 = new com.csgsystems.igpa.controls.CSGEdit();
        edtAddressLine1 = new com.csgsystems.igpa.controls.CSGEdit();
        lblAddressLine1 = new com.csgsystems.igpa.controls.CSGLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblStatementToFax = new com.csgsystems.igpa.controls.CSGLabel();
        edtStatementToFax = new com.csgsystems.igpa.controls.CSGEdit();
        lblStatementToEmail = new com.csgsystems.igpa.controls.CSGLabel();
        edtStatementToEmail = new com.csgsystems.igpa.controls.CSGEdit();
        lblContact1Name = new com.csgsystems.igpa.controls.CSGLabel();
        edtContact1Name = new com.csgsystems.igpa.controls.CSGEdit();
        lblContact1Phone = new com.csgsystems.igpa.controls.CSGLabel();
        edtContact1Phone = new com.csgsystems.igpa.controls.CSGEdit();
        lblContact2Name = new com.csgsystems.igpa.controls.CSGLabel();
        edtContact2Name = new com.csgsystems.igpa.controls.CSGEdit();
        lblContact2Phone = new com.csgsystems.igpa.controls.CSGLabel();
        edtContact2Phone = new com.csgsystems.igpa.controls.CSGEdit();
        jPanel5 = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 10, 0, 0)));
        setMinimumSize(new java.awt.Dimension(610, 270));
        setPreferredSize(new java.awt.Dimension(860, 360));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(new javax.swing.border.TitledBorder(ResourceManager.getString( "AccountAlternateAddress.title.AlternateAddress" )));
        jPanel1.setMinimumSize(new java.awt.Dimension(860, 250));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 350));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel2.setMinimumSize(new java.awt.Dimension(387, 245));
        jPanel2.setPreferredSize(new java.awt.Dimension(305, 205));
        edtCustGeocode.setAtomName("CustGeocode");
        edtCustGeocode.setDomainName("Account");
        edtCustGeocode.setEnabled(false);
        edtCustGeocode.setFocusable(false);
        edtCustGeocode.setMaximumSize(null);
        edtCustGeocode.setMinimumSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(edtCustGeocode, gridBagConstraints);

        lblCustGeocode.setLocalizationKey("AccountAlternateAddress.lblCustGeocode");
        lblCustGeocode.setMaximumSize(null);
        lblCustGeocode.setMinimumSize(new java.awt.Dimension(140, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        jPanel2.add(lblCustGeocode, gridBagConstraints);

        edtAddressLine3.setAttributeName("CustAddress3");
        edtAddressLine3.setDomainName("Account");
        edtAddressLine3.setMaximumSize(null);
        edtAddressLine3.setMinimumSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(edtAddressLine3, gridBagConstraints);

        cbFranchise.setAttributeName("CustFranchiseTaxCode");
        cbFranchise.setDomainName("Account");
        cbFranchise.setMaximumSize(null);
        cbFranchise.setMinimumSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(cbFranchise, gridBagConstraints);

        cbCountry.setAttributeName("CustCountryCode");
        cbCountry.setDomainName("Account");
        cbCountry.setMaximumSize(null);
        cbCountry.setMinimumSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(cbCountry, gridBagConstraints);

        lblFranchise.setLocalizationKey("Tax:");
        lblFranchise.setMinimumSize(new java.awt.Dimension(140, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel2.add(lblFranchise, gridBagConstraints);

        lblCountry.setLocalizationKey("AccountAlternateAddress.lblCountry");
        lblCountry.setMaximumSize(null);
        lblCountry.setMinimumSize(new java.awt.Dimension(140, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel2.add(lblCountry, gridBagConstraints);

        edtZipPostalCode.setAttributeName("CustZip");
        edtZipPostalCode.setDomainName("Account");
        edtZipPostalCode.setMaximumSize(null);
        edtZipPostalCode.setMinimumSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(edtZipPostalCode, gridBagConstraints);

        lblZipPostalCode.setLocalizationKey("Postcode:");
        lblZipPostalCode.setMinimumSize(new java.awt.Dimension(140, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel2.add(lblZipPostalCode, gridBagConstraints);

        lblStateProv.setLocalizationKey("State:");
        lblStateProv.setMinimumSize(new java.awt.Dimension(140, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel2.add(lblStateProv, gridBagConstraints);

        lblCity.setLocalizationKey("AccountAlternateAddress.lblCity");
        lblCity.setMaximumSize(null);
        lblCity.setMinimumSize(new java.awt.Dimension(140, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel2.add(lblCity, gridBagConstraints);

        edtStateProv.setAttributeName("CustState");
        edtStateProv.setDomainName("Account");
        edtStateProv.setMaximumSize(null);
        edtStateProv.setMinimumSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(edtStateProv, gridBagConstraints);

        edtCity.setAttributeName("CustCity");
        edtCity.setDomainName("Account");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(edtCity, gridBagConstraints);

        edtAddressLine2.setAttributeName("CustAddress2");
        edtAddressLine2.setDomainName("Account");
        edtAddressLine2.setMaximumSize(null);
        edtAddressLine2.setMinimumSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(edtAddressLine2, gridBagConstraints);

        edtAddressLine1.setAttributeName("CustAddress1");
        edtAddressLine1.setDomainName("Account");
        edtAddressLine1.setMaximumSize(null);
        edtAddressLine1.setMinimumSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel2.add(edtAddressLine1, gridBagConstraints);

        lblAddressLine1.setLocalizationKey("AccountAlternateAddress.lblAddressLine1");
        lblAddressLine1.setMaximumSize(null);
        lblAddressLine1.setMinimumSize(new java.awt.Dimension(140, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel2.add(lblAddressLine1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jPanel4, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 10);
        jPanel1.add(jPanel2, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel3.setMinimumSize(new java.awt.Dimension(387, 245));
        jPanel3.setPreferredSize(new java.awt.Dimension(305, 205));
        lblStatementToFax.setLocalizationKey("Fax:");
        lblStatementToFax.setMaximumSize(null);
        lblStatementToFax.setMinimumSize(new java.awt.Dimension(140, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel3.add(lblStatementToFax, gridBagConstraints);

        edtStatementToFax.setAttributeName("StatementToFaxno");
        edtStatementToFax.setDomainName("Account");
        edtStatementToFax.setMaximumSize(null);
        edtStatementToFax.setMinimumSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel3.add(edtStatementToFax, gridBagConstraints);

        lblStatementToEmail.setLocalizationKey("AccountSummaryDetail.vm.label.StatementEmail");
        lblStatementToEmail.setMinimumSize(new java.awt.Dimension(140, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel3.add(lblStatementToEmail, gridBagConstraints);

        edtStatementToEmail.setAttributeName("StatementToEmail");
        edtStatementToEmail.setDomainName("Account");
        edtStatementToEmail.setMaximumSize(null);
        edtStatementToEmail.setMinimumSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel3.add(edtStatementToEmail, gridBagConstraints);

        lblContact1Name.setLocalizationKey("Contact Person 1:");
        lblContact1Name.setMinimumSize(new java.awt.Dimension(140, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel3.add(lblContact1Name, gridBagConstraints);

        edtContact1Name.setAttributeName("Contact1Name");
        edtContact1Name.setAutoscrolls(false);
        edtContact1Name.setDomainName("Account");
        edtContact1Name.setMaximumSize(null);
        edtContact1Name.setMinimumSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel3.add(edtContact1Name, gridBagConstraints);

        lblContact1Phone.setLocalizationKey("Contact Person Phone 1:");
        lblContact1Phone.setMinimumSize(new java.awt.Dimension(140, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel3.add(lblContact1Phone, gridBagConstraints);

        edtContact1Phone.setAttributeName("Contact1Phone");
        edtContact1Phone.setDomainName("Account");
        edtContact1Phone.setMaximumSize(null);
        edtContact1Phone.setMinimumSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel3.add(edtContact1Phone, gridBagConstraints);

        lblContact2Name.setLocalizationKey("Contact Person 2:");
        lblContact2Name.setMinimumSize(new java.awt.Dimension(140, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel3.add(lblContact2Name, gridBagConstraints);

        edtContact2Name.setAttributeName("Contact2Name");
        edtContact2Name.setDomainName("Account");
        edtContact2Name.setMaximumSize(null);
        edtContact2Name.setMinimumSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel3.add(edtContact2Name, gridBagConstraints);

        lblContact2Phone.setLocalizationKey("Contact Person Phone 2:");
        lblContact2Phone.setMinimumSize(new java.awt.Dimension(140, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel3.add(lblContact2Phone, gridBagConstraints);

        edtContact2Phone.setAttributeName("Contact2Phone");
        edtContact2Phone.setDomainName("Account");
        edtContact2Phone.setMaximumSize(null);
        edtContact2Phone.setMinimumSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.7;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel3.add(edtContact2Phone, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel3.add(jPanel5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 5);
        jPanel1.add(jPanel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel1, gridBagConstraints);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.csgsystems.igpa.controls.CSGComboBox cbCountry;
    private com.csgsystems.igpa.controls.CSGComboBox cbFranchise;
    private com.csgsystems.igpa.controls.CSGEdit edtAddressLine1;
    private com.csgsystems.igpa.controls.CSGEdit edtAddressLine2;
    private com.csgsystems.igpa.controls.CSGEdit edtAddressLine3;
    private com.csgsystems.igpa.controls.CSGEdit edtCity;
    private com.csgsystems.igpa.controls.CSGEdit edtContact1Name;
    private com.csgsystems.igpa.controls.CSGEdit edtContact1Phone;
    private com.csgsystems.igpa.controls.CSGEdit edtContact2Name;
    private com.csgsystems.igpa.controls.CSGEdit edtContact2Phone;
    private com.csgsystems.igpa.controls.CSGEdit edtCustGeocode;
    private com.csgsystems.igpa.controls.CSGEdit edtStateProv;
    private com.csgsystems.igpa.controls.CSGEdit edtStatementToEmail;
    private com.csgsystems.igpa.controls.CSGEdit edtStatementToFax;
    private com.csgsystems.igpa.controls.CSGEdit edtZipPostalCode;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private com.csgsystems.igpa.controls.CSGLabel lblAddressLine1;
    private com.csgsystems.igpa.controls.CSGLabel lblCity;
    private com.csgsystems.igpa.controls.CSGLabel lblContact1Name;
    private com.csgsystems.igpa.controls.CSGLabel lblContact1Phone;
    private com.csgsystems.igpa.controls.CSGLabel lblContact2Name;
    private com.csgsystems.igpa.controls.CSGLabel lblContact2Phone;
    private com.csgsystems.igpa.controls.CSGLabel lblCountry;
    private com.csgsystems.igpa.controls.CSGLabel lblCustGeocode;
    private com.csgsystems.igpa.controls.CSGLabel lblFranchise;
    private com.csgsystems.igpa.controls.CSGLabel lblStateProv;
    private com.csgsystems.igpa.controls.CSGLabel lblStatementToEmail;
    private com.csgsystems.igpa.controls.CSGLabel lblStatementToFax;
    private com.csgsystems.igpa.controls.CSGLabel lblZipPostalCode;
    // End of variables declaration//GEN-END:variables
    
}
