/*
 * FavouriteArea.java
 *
 * Created on July 6, 2005, 2:05 PM
 */

package com.maxis.panel;

import com.csgsystems.igpa.forms.*;
import com.csgsystems.domain.framework.context.IContext;
import com.csgsystems.igpa.utils.ContextFinder;
import com.csgsystems.domain.framework.businessobject.IPersistentObject;
import com.csgsystems.igpa.controls.CSGNumberEdit;

/**
 *
 * @author  Pankaj Saini
 */
public class FavouriteArea extends javax.swing.JPanel implements ContextFormListener {
    
    protected ContextFinder ctxFinder = new ContextFinder(this);

    /** Creates new form FriendsAndFamily */
    public FavouriteArea() {
        initComponents();
    }
    
    public void contextFormStateChanged(ContextFormEvent evt){
        if (evt.getType() == ContextFormEvent.POST_OPEN){
            IPersistentObject obj = null;
                
            // get this panel's context
            IContext ctx = ctxFinder.findContext();
            obj = ctx.getObject("FavouriteArea", null);
            if (obj != null) {
                String label = obj.getAttributeDataAsString("Description");
                lblFASlot.setLocalizationKey(label);
            }
        }
    }  

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        ModifyFAPanel = new javax.swing.JPanel();
        lblFASlot = new com.csgsystems.igpa.controls.CSGLabel();
        cbFavouriteArea = new com.csgsystems.igpa.controls.CSGComboBox();

        setLayout(null);

        setPreferredSize(new java.awt.Dimension(320, 120));
        ModifyFAPanel.setLayout(null);

        ModifyFAPanel.setBorder(new javax.swing.border.TitledBorder(null, "Modify Favourite Areas"));
        ModifyFAPanel.setPreferredSize(new java.awt.Dimension(330, 150));
        lblFASlot.setLocalizationKey("Slot #i");
        ModifyFAPanel.add(lblFASlot);
        lblFASlot.setBounds(20, 40, 60, 20);

        cbFavouriteArea.setAttributeName("Area");
        cbFavouriteArea.setDomainName("FavouriteArea");
        ModifyFAPanel.add(cbFavouriteArea);
        cbFavouriteArea.setBounds(100, 40, 150, 20);

        add(ModifyFAPanel);
        ModifyFAPanel.setBounds(10, 10, 290, 100);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ModifyFAPanel;
    private com.csgsystems.igpa.controls.CSGComboBox cbFavouriteArea;
    private com.csgsystems.igpa.controls.CSGLabel lblFASlot;
    // End of variables declaration//GEN-END:variables
    
}
