/*
 * FriendsAndFamily.java
 *
 * Created on June 15, 2005, 2:05 PM
 */

package com.maxis.panel;

import com.csgsystems.igpa.forms.*;
import com.csgsystems.domain.framework.context.IContext;
import com.csgsystems.igpa.utils.ContextFinder;
import com.csgsystems.domain.framework.businessobject.IPersistentObject;
import com.csgsystems.igpa.controls.CSGNumberEdit;

/**
 *
 * @author  Pankaj Saini
 */
public class FnF extends javax.swing.JPanel implements ContextFormListener {
    
    protected ContextFinder ctxFinder = new ContextFinder(this);

    /** Creates new form FriendsAndFamily */
    public FnF() {
        initComponents();
//        this.edtFnFNumber.setControlFormat(CSGNumberEdit.UNFORMATTED_INTEGER_FORMAT);
    }
    
    public void contextFormStateChanged(ContextFormEvent evt){
        if (evt.getType() == ContextFormEvent.POST_OPEN){
            IPersistentObject obj = null;
                
            // get this panel's context
            IContext ctx = ctxFinder.findContext();
            obj = ctx.getObject("FriendsAndFamily", null);
            if (obj != null) {
                String label = obj.getAttributeDataAsString("Description");
                lblFnFSlot.setLocalizationKey(label);
            }
        }
    }  

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        ModifyFnFPanel = new javax.swing.JPanel();
        lblFnFSlot = new com.csgsystems.igpa.controls.CSGLabel();
        cSGComboBox1 = new com.csgsystems.igpa.controls.CSGComboBox();

        setLayout(null);

        setPreferredSize(new java.awt.Dimension(320, 120));
        ModifyFnFPanel.setLayout(null);

        ModifyFnFPanel.setBorder(new javax.swing.border.TitledBorder("Create Special IDD"));
        ModifyFnFPanel.setPreferredSize(new java.awt.Dimension(330, 150));
        lblFnFSlot.setLocalizationKey("Favourite Country:");
        lblFnFSlot.setMinimumSize(new java.awt.Dimension(100, 20));
        lblFnFSlot.setPreferredSize(new java.awt.Dimension(120, 20));
        ModifyFnFPanel.add(lblFnFSlot);
        lblFnFSlot.setBounds(10, 40, 120, 20);

        cSGComboBox1.setAttributeName("Zone");
        cSGComboBox1.setDomainName("GenericDomain");
        ModifyFnFPanel.add(cSGComboBox1);
        cSGComboBox1.setBounds(120, 40, 150, 20);

        add(ModifyFnFPanel);
        ModifyFnFPanel.setBounds(10, 10, 290, 100);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ModifyFnFPanel;
    private com.csgsystems.igpa.controls.CSGComboBox cSGComboBox1;
    private com.csgsystems.igpa.controls.CSGLabel lblFnFSlot;
    // End of variables declaration//GEN-END:variables
    
}
