/*
 * IcBrnCheck.java
 *
 * Created on August 10, 2005, 7:07 PM
 */

package com.maxis.panel;

/**
 * New panel to input data for internal search
 * Shows 2 fields for entering type and values
 * @author  Pankaj Saini
 */
public class IcBrnCheck extends javax.swing.JPanel {
    
    /** Creates new form TestIcBrnCheck */
    public IcBrnCheck() {
        initComponents();
    }
        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        extIdTypeLabel = new com.csgsystems.igpa.controls.CSGLabel();
        acctExtId = new com.csgsystems.igpa.controls.CSGEdit();
        acctExtIdLabel = new com.csgsystems.igpa.controls.CSGLabel();
        extIdType = new com.csgsystems.igpa.controls.CSGComboBox();

        setLayout(null);

        setPreferredSize(new java.awt.Dimension(290, 130));
        jPanel1.setLayout(null);

        jPanel1.setBorder(new javax.swing.border.TitledBorder("IC/BRN Check"));
        extIdTypeLabel.setLocalizationKey("ID Type:");
        jPanel1.add(extIdTypeLabel);
        extIdTypeLabel.setBounds(20, 30, 50, 20);

        acctExtId.setText("cSGEdit1");
        acctExtId.setAttributeName("Value");
        acctExtId.setDomainName("GenericDomain");
        acctExtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                acctExtIdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                acctExtIdKeyReleased(evt);
            }
        });

        jPanel1.add(acctExtId);
        acctExtId.setBounds(90, 60, 150, 20);

        acctExtIdLabel.setLocalizationKey("ID No:");
        jPanel1.add(acctExtIdLabel);
        acctExtIdLabel.setBounds(20, 60, 50, 20);

        extIdType.setAttributeName("Type");
        extIdType.setDomainName("GenericDomain");
        jPanel1.add(extIdType);
        extIdType.setBounds(90, 30, 150, 20);

        add(jPanel1);
        jPanel1.setBounds(10, 10, 270, 100);

    }
    // </editor-fold>//GEN-END:initComponents

    private void acctExtIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_acctExtIdKeyPressed
// TODO add your handling code here:
    }//GEN-LAST:event_acctExtIdKeyPressed

    private void acctExtIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_acctExtIdKeyReleased
// TODO add your handling code here:
        acctExtId.updateObject();
    }//GEN-LAST:event_acctExtIdKeyReleased
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.csgsystems.igpa.controls.CSGEdit acctExtId;
    private com.csgsystems.igpa.controls.CSGLabel acctExtIdLabel;
    private com.csgsystems.igpa.controls.CSGComboBox extIdType;
    private com.csgsystems.igpa.controls.CSGLabel extIdTypeLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
