/*
 * InternalSearchResults.java
 *
 * Created on October 7, 2005, 2:41 PM
 */

package com.maxis.panel;

import com.csgsystems.bp.utilities.TemplateUtility;
import com.csgsystems.igpa.utils.ContextFinder;
import com.csgsystems.domain.framework.context.IContext;
import com.csgsystems.domain.framework.businessobject.IPersistentCollection;
import com.csgsystems.domain.framework.businessobject.IPersistentObject;
import com.csgsystems.igpa.forms.*;
import javax.swing.JButton;

/**
 *
 * @author  prev01
 */
public class InternalSearchResults extends AbstractHTMLPanel implements ContextFormListener {
    private ContextFinder ctxFinder = new ContextFinder(this);
    private boolean fraud = false;
    
    /** Creates new form OrderConfirmation */
    public InternalSearchResults() {
        initComponents();
        velInternalSearchResults.addExtraVelocityContextTopic("TemplateUtility", new TemplateUtility());
        velInternalSearchResults.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
          public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt){
            NavigationHyperlinkFilter(evt, velInternalSearchResults);
          }
        });
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        velInternalSearchResults = new com.csgsystems.igpa.controls.CSGVelocityHTMLEP();

        setLayout(new java.awt.BorderLayout());

        setPreferredSize(new java.awt.Dimension(900, 620));

        velInternalSearchResults.setVelocityTemplateUri("template/MXSInternalSearchResults.vm");
        add(velInternalSearchResults, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents
    
    public void contextFormStateChanged(ContextFormEvent evt){
        
        if (evt.getType() == ContextFormEvent.READY) {
            fraud = false;
            IContext ctx = ctxFinder.findContext();
            IPersistentCollection searchResults = (IPersistentCollection)ctx.getObject("MXSAccountSearchList");
            for ( int i = 0; i < searchResults.getCount(); i++ ) {
                IPersistentObject account = searchResults.getAt(i).getObject("Account");
                if ( account.getAttributeDataAsInteger("CollectionStatus") == 3 ) {
                    fraud = true;
                }
            }
            
            if ( fraud ) {
                ctxFinder.enableButton(ICSGContextForm.NEXT_BUTTON, false);
                ctxFinder.enableButton(ICSGContextForm.PREVIOUS_BUTTON, false);
            }
            
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.csgsystems.igpa.controls.CSGVelocityHTMLEP velInternalSearchResults;
    // End of variables declaration//GEN-END:variables
    
}
