/*
 * InternalSearchServieDetails.java
 *
 * Created on October 10, 2005, 4:40 PM
 */

package com.maxis.panel;

import com.csgsystems.bp.utilities.TemplateUtility;

/**
 *
 * @author  prev01
 */
public class InternalSearchServiceDetails extends AbstractHTMLPanel {
    
    /** Creates new form InternalSearchServiceDetails */
    public InternalSearchServiceDetails() {
        initComponents();
        velInternalSearchResults.addExtraVelocityContextTopic("TemplateUtility", new TemplateUtility());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        velInternalSearchResults = new com.csgsystems.igpa.controls.CSGVelocityHTMLEP();

        setLayout(new java.awt.BorderLayout());

        setPreferredSize(new java.awt.Dimension(900, 620));

        velInternalSearchResults.setVelocityTemplateUri("template/MXSInternalSearchServiceDetails.vm");
        add(velInternalSearchResults, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.csgsystems.igpa.controls.CSGVelocityHTMLEP velInternalSearchResults;
    // End of variables declaration//GEN-END:variables
    
}
