/*
 * OrderConfirmation.java
 *
 * Created on November 23, 2002, 11:48 AM
 */

package com.maxis.panel;

import com.csgsystems.bp.utilities.TemplateUtility;

/**
 *
 * @author  prev01
 */
public class NewCustAcqAccountDetails extends AbstractHTMLPanel {
    
    /** Creates new form OrderConfirmation */
    public NewCustAcqAccountDetails() {
        initComponents();
        velNewCustAcqAccountDetails.addHyperlinkListener(new javax.swing.event.HyperlinkListener() {
            public void hyperlinkUpdate(javax.swing.event.HyperlinkEvent evt){
                DetailHyperlinkFilter(evt, velNewCustAcqAccountDetails);
            }
        });
        velNewCustAcqAccountDetails.addExtraVelocityContextTopic("TemplateUtility", new TemplateUtility());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        velNewCustAcqAccountDetails = new com.csgsystems.igpa.controls.CSGVelocityHTMLEP();

        setLayout(new java.awt.BorderLayout());

        setPreferredSize(new java.awt.Dimension(900, 620));

        velNewCustAcqAccountDetails.setVelocityTemplateUri("template/MXSAccountLocate.vm");
        add(velNewCustAcqAccountDetails, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.csgsystems.igpa.controls.CSGVelocityHTMLEP velNewCustAcqAccountDetails;
    // End of variables declaration//GEN-END:variables
    
}
