/*
 * PrepaidNoteSearch.java
 *
 * Created on June 13, 2005, 2:49 PM
 */

package com.maxis.panel;

import com.csgsystems.igpa.forms.ContextFormEvent;
import com.csgsystems.igpa.forms.ContextFormListener;
import com.csgsystems.igpa.utils.ContextFinder;
import com.csgsystems.domain.framework.context.IContext;

/**
 *
 * @author  Pankaj Saini
 */
public class PrepaidNoteSearch extends javax.swing.JPanel {

    ContextFinder ctxFinder = new ContextFinder(this);

    /** Creates new form PrepaidNoteSearch */
    public PrepaidNoteSearch() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        lblNoteCode = new com.csgsystems.igpa.controls.CSGLabel();
        cbReason = new com.csgsystems.igpa.controls.CSGComboBox();
        lblNoteText = new com.csgsystems.igpa.controls.CSGLabel();
        edtNoteText = new com.csgsystems.igpa.controls.CSGEdit();
        lblReason = new com.csgsystems.igpa.controls.CSGLabel();
        cbNoteCode = new com.csgsystems.igpa.controls.CSGComboBox();
        lblRemarks = new com.csgsystems.igpa.controls.CSGLabel();
        edtRemarks = new com.csgsystems.igpa.controls.CSGEdit();
        lblUserId = new com.csgsystems.igpa.controls.CSGLabel();
        edtUserId = new com.csgsystems.igpa.controls.CSGEdit();
        lblDate = new com.csgsystems.igpa.controls.CSGLabel();
        edtDate = new com.csgsystems.igpa.controls.CSGDateEdit();

        setLayout(null);

        setPreferredSize(new java.awt.Dimension(330, 220));
        lblNoteCode.setLocalizationKey("Note Code:");
        add(lblNoteCode);
        lblNoteCode.setBounds(20, 20, 100, 20);

        cbReason.setAttributeName("Reason");
        cbReason.setDomainName("PrepaidNotesList");
        cbReason.setDomainSubtype("Service");
        add(cbReason);
        cbReason.setBounds(150, 80, 150, 20);

        lblNoteText.setLocalizationKey("Note Text:");
        add(lblNoteText);
        lblNoteText.setBounds(20, 50, 100, 20);

        edtNoteText.setText("cSGEdit1");
        edtNoteText.setAttributeName("NoteText");
        edtNoteText.setDomainName("PrepaidNotesList");
        edtNoteText.setDomainSubtype("Service");
        add(edtNoteText);
        edtNoteText.setBounds(150, 50, 150, 20);

        lblReason.setLocalizationKey("Reason:");
        add(lblReason);
        lblReason.setBounds(20, 80, 100, 20);

        cbNoteCode.setAttributeName("NoteCode");
        cbNoteCode.setDomainName("PrepaidNotesList");
        cbNoteCode.setDomainSubtype("Service");
        add(cbNoteCode);
        cbNoteCode.setBounds(150, 20, 150, 20);

        lblRemarks.setLocalizationKey("Remarks:");
        add(lblRemarks);
        lblRemarks.setBounds(20, 110, 100, 20);

        edtRemarks.setText("cSGEdit1");
        edtRemarks.setAttributeName("Remarks");
        edtRemarks.setDomainName("PrepaidNotesList");
        edtRemarks.setDomainSubtype("Service");
        add(edtRemarks);
        edtRemarks.setBounds(150, 110, 150, 20);

        lblUserId.setLocalizationKey("User ID:");
        add(lblUserId);
        lblUserId.setBounds(20, 140, 90, 20);

        edtUserId.setText("cSGEdit1");
        edtUserId.setAttributeName("ChangeWho");
        edtUserId.setDomainName("PrepaidNotesList");
        edtUserId.setDomainSubtype("Service");
        add(edtUserId);
        edtUserId.setBounds(150, 140, 150, 20);

        lblDate.setLocalizationKey("Date:");
        add(lblDate);
        lblDate.setBounds(20, 170, 80, 20);

        edtDate.setAttributeName("NoteDate");
        edtDate.setDomainName("PrepaidNotesList");
        edtDate.setDomainSubtype("Service");
        add(edtDate);
        edtDate.setBounds(150, 170, 80, 20);

    }
    // </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.csgsystems.igpa.controls.CSGComboBox cbNoteCode;
    private com.csgsystems.igpa.controls.CSGComboBox cbReason;
    private com.csgsystems.igpa.controls.CSGDateEdit edtDate;
    private com.csgsystems.igpa.controls.CSGEdit edtNoteText;
    private com.csgsystems.igpa.controls.CSGEdit edtRemarks;
    private com.csgsystems.igpa.controls.CSGEdit edtUserId;
    private com.csgsystems.igpa.controls.CSGLabel lblDate;
    private com.csgsystems.igpa.controls.CSGLabel lblNoteCode;
    private com.csgsystems.igpa.controls.CSGLabel lblNoteText;
    private com.csgsystems.igpa.controls.CSGLabel lblReason;
    private com.csgsystems.igpa.controls.CSGLabel lblRemarks;
    private com.csgsystems.igpa.controls.CSGLabel lblUserId;
    // End of variables declaration//GEN-END:variables
}
