/*
 * TestIcBrnCheck.java
 *
 * Created on August 10, 2005, 7:07 PM
 */

package com.maxis.panel;

/**
 *
 * @author  Pankaj Saini
 */
public class TestIcBrnCheck extends javax.swing.JPanel {
    
    /** Creates new form TestIcBrnCheck */
    public TestIcBrnCheck() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        cSGLabel1 = new com.csgsystems.igpa.controls.CSGLabel();
        cSGEdit1 = new com.csgsystems.igpa.controls.CSGEdit();
        cSGLabel2 = new com.csgsystems.igpa.controls.CSGLabel();
        cSGComboBox1 = new com.csgsystems.igpa.controls.CSGComboBox();

        setLayout(null);

        setPreferredSize(new java.awt.Dimension(290, 130));
        jPanel1.setLayout(null);

        jPanel1.setBorder(new javax.swing.border.TitledBorder("IC/BRN Check"));
        cSGLabel1.setLocalizationKey("ID Type:");
        jPanel1.add(cSGLabel1);
        cSGLabel1.setBounds(20, 30, 50, 20);

        cSGEdit1.setText("cSGEdit1");
        cSGEdit1.setAttributeName("Value");
        cSGEdit1.setDomainName("GenericDomain");
        jPanel1.add(cSGEdit1);
        cSGEdit1.setBounds(90, 60, 150, 20);

        cSGLabel2.setLocalizationKey("ID Value:");
        jPanel1.add(cSGLabel2);
        cSGLabel2.setBounds(20, 60, 50, 20);

        cSGComboBox1.setAttributeName("Type");
        cSGComboBox1.setDomainName("GenericDomain");
        jPanel1.add(cSGComboBox1);
        cSGComboBox1.setBounds(90, 30, 150, 20);

        add(jPanel1);
        jPanel1.setBounds(10, 10, 270, 100);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.csgsystems.igpa.controls.CSGComboBox cSGComboBox1;
    private com.csgsystems.igpa.controls.CSGEdit cSGEdit1;
    private com.csgsystems.igpa.controls.CSGLabel cSGLabel1;
    private com.csgsystems.igpa.controls.CSGLabel cSGLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
}
